name: Check Pull Request Quality

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Commit Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Commits
        uses: Ferlab-Ste-Justine/action-commit-lint@v2
  tests:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Use Dependencies Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure we can build the image
        run: docker build -t test:test .
